const {chromium}=require('playwright-core');
const fs=require('fs');
const assert=require('assert');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1540,height:940},deviceScaleFactor:1});
 const session=JSON.parse(fs.readFileSync('test-output/session.json','utf8'));
 await page.exposeFunction('initialLog',()=>null);
 const exported=[];
 await page.exposeFunction('saveExport',o=> {exported.push(o);return '';});
 await page.exposeFunction('openLog',()=>session);
 await page.exposeFunction('importLogText',()=>{throw new Error('Unsupported profile');});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync('ui/index.html','utf8').replace('/*STYLE*/',()=>fs.readFileSync('ui/style.css','utf8')).replace('/*SCRIPT*/',()=>fs.readFileSync('ui/app.js','utf8'));
 await page.setContent(html);
 await page.waitForFunction(()=>document.getElementById('busy').hidden);
 assert(await page.locator('#emptyState').isVisible());
 assert(await page.locator('#csvBtn').isDisabled());
 assert(await page.locator('#txtBtn').isDisabled());
 assert.equal(await page.locator('#fileName').innerText(),'Файл не открыт');
 await page.screenshot({path:'test-output/studio-empty.png'});
 assert.deepEqual(errors,[]);
 console.log('PASS: start without a demo log; empty workspace and disabled exports.');
 await page.locator('#openBtn').click();
 await page.waitForFunction(()=>document.getElementById('fileDetail').textContent.includes('3540')||document.getElementById('fileDetail').textContent.includes('3 540')||document.getElementById('fileDetail').textContent.includes('3 540'));
 console.log('initial',await page.evaluate(()=>({size:[innerWidth,innerHeight],file:document.getElementById('fileDetail').textContent,channels:document.getElementById('channelCount').textContent,charts:document.querySelectorAll('.chart-canvas').length,kpis:[...document.querySelectorAll('.kpi-main b')].map(e=>e.textContent)})));
 await page.screenshot({path:'test-output/studio-initial.png'});
 const c=page.locator('.chart-canvas').first(),box=await c.boundingBox();
 await page.mouse.move(box.x+box.width*.32,box.y+box.height*.45);await page.mouse.down();await page.mouse.move(box.x+box.width*.58,box.y+box.height*.48,{steps:10});await page.mouse.up();
 assert.equal(await page.locator('#zoomSelection').isEnabled(),true);
 console.log('selection',await page.locator('#selectionLabel').innerText());
 await page.locator('#zoomSelection').click();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.4);await page.mouse.wheel(0,-200);
 await page.screenshot({path:'test-output/studio-selection.png'});
 await page.locator('[data-view="table"]').click();assert.equal(await page.locator('#dataTable tbody tr').count(),80);await page.locator('#nextPage').click();assert.equal(await page.locator('#pageLabel').innerText(),'2 / 45');
 await page.screenshot({path:'test-output/studio-table.png'});
 await page.locator('#qualityBtn').click();assert((await page.locator('.event-row').count())>=38);console.log('quality events',await page.locator('.event-row').count());await page.locator('.event-row').first().click();
 await page.locator('#searchInput').fill('коррекции');const matches=await page.locator('.channel-row').count();assert(matches>=2);console.log('search matches',matches);await page.locator('#searchInput').fill('');
 await page.locator('#preset').selectOption('mixture');assert.equal(await page.locator('.chart-canvas').count(),4);
 await page.locator('[data-filter="flags"]').click();assert((await page.locator('.channel-row').count())>30);await page.locator('[data-filter="numbers"]').click();
 await page.locator('#csvBtn').click();assert(await page.locator('#exportDialog').isVisible());console.log('export preview',await page.locator('#exportPreview').innerText());await page.locator('#exportParams').selectOption('charts');
 await page.locator('#confirmExport').click();await page.waitForTimeout(100);assert.equal(exported.length,1);const exportArgs=exported[0];assert.equal(exportArgs.format,'csv');assert.equal(exportArgs.parameters.length,4);assert(exportArgs.end>exportArgs.start);
 await page.locator('#exportDialog button[value="cancel"]').last().click();
 await page.locator('#txtBtn').click();assert.equal(await page.locator('#excelField').isVisible(),false);await page.locator('#exportDialog button[value="cancel"]').last().click();
 await page.locator('#clearSelection').click();await page.locator('#fitBtn').click();await page.locator('#preset').selectOption('engine');await page.locator('#playSpeed').selectOption('16');await page.locator('#playBtn').click();await page.waitForTimeout(300);await page.locator('#playBtn').click();
 await page.keyboard.press('End');console.log('last frame',await page.locator('#frameIndex').innerText());await page.keyboard.press('Home');
 // An import error must leave the current session intact.
 const bad=await page.evaluate(async()=>{try{await window.importLogText('wrong.log','ВАЗ: Ителма M74CAN MAP\nTime: 00:00:00\nSend: 220001\nReceive: 62 00 01 04');return 'accepted';}catch(e){return String(e)}});assert.notEqual(bad,'accepted');
 assert.deepEqual(errors,[]);console.log('PASS: UI interactions, export options, rejected profile. Errors:',errors);
 await page.screenshot({path:'test-output/studio-final.png'});
 await page.setViewportSize({width:1180,height:701});await page.screenshot({path:'test-output/studio-small.png'});
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
